// Generated by CoffeeScript 1.7.1
(function() {
  describe("text index", function() {
    return it('expect true to be true', function() {
      return expect(test()).toBe(true);
    });
  });

}).call(this);
